server:
  port: 8090

spring:
  data:
    mongodb:
      database: myapp
      port: 27017
      host: localhost
      auto-index-creation: true
      authentication-database: admin
#      username: root
#      password: rootpassword
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true