version: '3.7'

services:
  mongodb:
    container_name: demo_mongodb_local_dev
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword